### ISSUE TITLE
Error using Rust nightly on Windows.

### ISSUE THREAD

**Issue by Mixthos** [AtomLinter/linter-rust#95] opened 2016-12-11 00:24 UTC
For some reason,  the linter gives this error message on nightly, but not on stable;

```
Failed to run cargo with exit code 3221225781
with args:
 build -j 2 --manifest-path D:\Projects\tamr\tamr\Cargo.toml --message-format json
See console for more information
```

If I run the command in the console, this is the error:

```
cargo build -j 2 --manifest-path D:\Projects\tamr\tamr\Cargo.toml --message-format json
error: the manifest-path must be a path to a Cargo.toml file
```

The issue seems to be that the manifest path is not surrounded by quotes. It also works fine if I use `/` instead of `\`.

What confuses me is that the linter works on stable Rust, even though cargo doesn't accept the unquoted path there, either. Does `linter-rust` quote the path on stable, but not on nightly?

**Comment by White-Oak** [comment] 2016-12-12 08:38
@Mixthos it would be great if you could specify the versions of Rust used as well. Thanks for the issue!

**Comment by Mixthos** [comment] 2016-12-23 03:52
Sorry for the late response.

One of the versions I used when I got the error was `rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)`. It does work again in `rustc 1.15.0-nightly (71c06a56a 2016-12-18)`.

I guess this can be closed?

**Comment by White-Oak** [comment] 2016-12-23 10:20
@Mixthos I'm happy it got resolved for you! Thanks for the response. I'll leave this opened for a while and will try later on Windows with that exact version.

**Comment by White-Oak** [comment] 2016-12-24 20:24
Well, I am not able to reproduce it..

**Comment by Mixthos** [comment] 2016-12-25 01:46
I am using Windows 10 Pro and the target `x86_64-pc-windows-gnu`, if that helps.

**Comment by Arcanemagus** [comment] 2019-01-17 19:04
Closing due to the above issue with reproducing this, and the age of the issue. If you are still having issues please let us know!

**Closed by Arcanemagus** 2019-01-17 19:04 UTC
Labels: bug
