### ISSUE TITLE
No lints using rustup

### ISSUE THREAD

**Issue by leshow** [AtomLinter/linter-rust#73] opened 2016-09-02 02:01 UTC
I'm not able to get any lint output. 

I'm using rustup and rustc nightly:
```
>  ~/Development/rust/ricem [master] rustup --version
rustup 0.6.3 (a0e2132 2016-08-28)
>  ~/Development/rust/ricem [master] rustc --version
rustc 1.13.0-nightly (2c01bb885 2016-08-31)
```

Atom isn't showing any errors, is there a way to get some output to figure out whats going on?

```
>  ~/Development/rust/ricem [master] apm list
...
Community Packages (73) /home/leshow/.atom/packages
├── activate-power-mode@0.8.1
├── atom-beautify@0.29.11
├── atom-html-preview@0.1.22
├── atom-material-syntax@0.4.6
├── atom-material-syntax-dark@0.2.5
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.3.6
├── atom-ternjs@0.15.0
├── atom-typescript@10.1.6
├── autocomplete-elixir@1.5.14
├── autocomplete-go@1.1.1
├── autocomplete-haskell@0.6.6
├── autocomplete-paths@1.0.2
├── autocomplete-php@0.3.7
├── builder-go@1.0.1
├── color-picker@2.2.2
├── duotone-light-syntax@1.0.0
├── editorconfig@1.4.1
├── environment@1.2.0
├── file-icons@1.7.19
├── filesize@0.4.2
├── flatland-dark@0.1.6
├── flatland-dark-ui@0.2.4
├── git-log@0.4.1
├── git-plus@5.16.2
├── go-config@1.2.3
├── go-debug@0.1.22
├── go-get@1.0.4
├── go-plus@4.2.0
├── godoc@0.4.0
├── gofmt@1.1.8
├── gometalinter-linter@1.1.1
├── gorename@1.0.3
├── graphite-ui@0.15.1
├── haskell-ghc-mod@1.17.2
├── haskell-hoogle@0.1.3
├── highlight-line@0.11.1
├── ide-haskell@1.8.1
├── isotope-ui@2.7.1
├── language-babel@2.36.2
├── language-elixir@0.16.0
├── language-elm@1.5.0
├── language-haskell@1.9.7
├── language-javascript-jsx@0.3.7
├── language-ocaml@1.1.2
├── language-rust@0.4.6
├── linter@1.11.16
├── linter-elm-make@0.17.2
├── linter-erlc@0.3.0
├── linter-eslint@7.2.4
├── linter-hlint@0.5.0
├── linter-rust@0.5.5
├── linter-tslint@0.11.1
├── markdown-helpers@0.3.0
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── monokai@0.18.0
├── monokai-seti@0.7.0
├── navigator-godef@1.0.4
├── php-debug@0.2.3
├── pigments@0.34.0
├── racer@0.20.0
├── seti-monokai@0.3.1
├── seti-syntax@1.0.1
├── seti-ui@1.3.2
├── shadow@0.1.0
├── spacegray-dark-neue-syntax@1.3.0
├── spacegray-dark-ui@0.12.0
├── tester-go@1.0.6
├── unity-dark-ui@2.0.9
├── unity-ui@2.1.5
├── yeti-syntax@0.1.2
└── yeti-ui@0.1.6
```

**Comment by leshow** [comment] 2016-09-02 02:20
It seems to work when I set the cargo command to `rustc` instead of `build` why would that be?

**Comment by White-Oak** [comment] 2016-09-02 09:48
Is your OS Windows?

**Comment by leshow** [comment] 2016-09-02 13:30
No, I'm on ArchLinux, using the latest Atom

**Comment by White-Oak** [comment] 2016-09-02 17:42
A duplicate of #69

**Comment by Arcanemagus** [comment] 2016-09-02 19:20
Marking as closed then, thanks for troubleshooting that 😉.

**Closed by Arcanemagus** 2016-09-02 19:20 UTC
