### ISSUE TITLE
Prevents cargo from building while Atom is open

### ISSUE THREAD

**Issue by Xaeroxe23** [AtomLinter/linter-rust#85] opened 2016-10-21 21:42 UTC
while editing my code with the plugin enabled if I open a command prompt and type "cargo run" the build is blocked until I close atom since the build directory is locked.

Environment info:
Windows 10
Shell used to run the command: cmd.exe

To reproduce: With plugin enabled edit an rs file with Atom in a cargo project then save it.  Then without closing the file or Atom, open a command prompt in the cargo project directory and run "cargo run" it should show a teal "blocking" error until Atom is closed.  This doesn't occur though if linter-rust is disabled or uninstalled.

**Comment by colin-kiegel** [comment] 2016-10-22 04:43
If it only blocks _temporarilly_ it's not a bug. This plugin runs the rust compiler on file changes, which blocks itself to avoid race conditions.

How long does your build typically take?
What happens if you just wait a bit longer then that when the blocking occurs?
Please also take a look at the processes running. If cargo or rustc is working, the blocking is the correct and intended behaviour.

**Comment by Xaeroxe23** [comment] 2016-10-22 13:47
The block is long enough to be a nuisance, it blocks way longer than my build typically takes though.  cargo is running, however if it's really going to take that long I need some way to cancel the cargo process from the plugin.  The plugin is no good to me if I have to use task manager to kill the cargo process everytime I want to build.

**Comment by Xaeroxe23** [comment] 2016-10-22 13:49
It has occurred to me that the length of the blocking could also have something to do with this issue: https://github.com/AtomLinter/linter-rust/issues/77

**Comment by White-Oak** [comment] 2016-10-22 23:00
@Xaeroxe23 yes, it seems that it is caused by #77. There is an open PR #84, that is going to fix that on nightlies. We still have some questions to solve (in particullar, how to cache "toolchains' versions"  between several lints), but the fix has already been done, so I hope it's not that long before it will be in the next release. 

Sorry for the inconvenience, and thanks for the report!

**Closed** 2016-10-24 22:45 UTC
Labels: duplicate
